In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv('books.csv')
users = pd.read_csv('users.csv')
ratings = pd.read_csv('ratings.csv')

C:\Users\Pranny21\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...

In [4]:
users

        User-ID                            Location   Age
0             1                  nyc, new york, usa   NaN
1             2           stockton, california, usa  18.0
2             3     moscow, yukon territory, russia   NaN
3             4           porto, v.n.gaia, portugal  17.0
4             5  farnborough, hants, united kingdom   NaN
...         ...                                 ...   ...
278853   278854               portland, oregon, usa   NaN
278854   278855  tacoma, washington, united kingdom  50.0
278855   278856           brampton, ontario, canada   NaN
278856   278857           knoxville, tennessee, usa   NaN
278857   278858                dublin, n/a, ireland   NaN

[278858 rows x 3 columns]

In [5]:
ratings.head(10)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
5   276733  2080674722            0
6   276736  3257224281            8
7   276737  0600570967            6
8   276744  038550120X            7
9   276745   342310538           10

In [6]:
print(books.shape)
print(ratings.shape)
print(users.shape)

(271360, 8)
(1149780, 3)
(278858, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [10]:
books.duplicated().sum()

0

In [11]:
ratings.duplicated().sum()

0

In [12]:
users.duplicated().sum()

0

In [13]:
x=books[books["Book-Author"] == "Agatha Christie"]

In [14]:
x

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1855,0451200993,Sleeping Murder (Miss Marple Mysteries (Paperb...,Agatha Christie,2000,New American Library,http://images.amazon.com/images/P/0451200993.0...,http://images.amazon.com/images/P/0451200993.0...,http://images.amazon.com/images/P/0451200993.0...
2012,0671555235,A Caribbean Mystery,Agatha Christie,1984,Pocket,http://images.amazon.com/images/P/0671555235.0...,http://images.amazon.com/images/P/0671555235.0...,http://images.amazon.com/images/P/0671555235.0...
2355,0425173755,Murder on the Orient Express (Hercule Poirot M...,Agatha Christie,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425173755.0...,http://images.amazon.com/images/P/0425173755.0...,http://images.amazon.com/images/P/0425173755.0...
2356,0451199871,The Body in the Library (Miss Marple Mysteries...,Agatha Christie,2000,Signet Book,http://images.amazon.com/images/P/0451199871.0...,http://images.amazon.com/images/P/0451199871.0...,http://images.amazon.com/images/P/0451199871.0...
2569,067170463X,Murder on the Orient Express,Agatha Christie,1978,Pocket Books,http://images.amazon.com/images/P/067170463X.0...,http://images.amazon.com/images/P/067170463X.0...,http://images.amazon.com/images/P/067170463X.0...
...,...,...,...,...,...,...,...,...
270319,2702400787,Le couteau sur la nuque,Agatha Christie,1979,Librairie des Champs-ElysÃ?Â©es,http://images.amazon.com/images/P/2702400787.0...,http://images.amazon.com/images/P/2702400787.0...,http://images.amazon.com/images/P/2702400787.0...
270519,0671494538,ENDLESS NIGHT,Agatha Christie,1983,Pocket,http://images.amazon.com/images/P/0671494538.0...,http://images.amazon.com/images/P/0671494538.0...,http://images.amazon.com/images/P/0671494538.0...
271094,8427201079,El Misterio De Sittaford,Agatha Christie,0,Editorial Molino,http://images.amazon.com/images/P/8427201079.0...,http://images.amazon.com/images/P/8427201079.0...,http://images.amazon.com/images/P/8427201079.0...
271095,8427285280,Poirot en Egipto,Agatha Christie,1996,Downtown Book Center,http://images.amazon.com/images/P/8427285280.0...,http://images.amazon.com/images/P/8427285280.0...,http://images.amazon.com/images/P/8427285280.0...
271250,073943828X,Murder at the Manor (Mystery Guild Lost Classi...,Agatha Christie,1929,Dodd Mead &amp; Company,http://images.amazon.com/images/P/073943828X.0...,http://images.amazon.com/images/P/073943828X.0...,http://images.amazon.com/images/P/073943828X.0...

In [15]:
books["Publisher"].mode()

0    Harlequin
dtype: object

In [16]:
ratings.describe()

            User-ID   Book-Rating
count  1.149780e+06  1.149780e+06
mean   1.403864e+05  2.866950e+00
std    8.056228e+04  3.854184e+00
min    2.000000e+00  0.000000e+00
25%    7.034500e+04  0.000000e+00
50%    1.410100e+05  0.000000e+00
75%    2.110280e+05  7.000000e+00
max    2.788540e+05  1.000000e+01

In [17]:
books["Book-Author"].mode()

0    Agatha Christie
dtype: object

In [18]:
x=ratings[ratings["ISBN"] == "0425173755"]

In [19]:
x["Book-Rating"].mean()

4.617647058823529

In [20]:
len(users["Location"].unique())

57339

## Popularity based recommender system

In [21]:
ratings_with_name=ratings.merge(books,on="ISBN")

In [22]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [23]:
num_rating_df=ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()

In [24]:
num_rating_df

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [25]:
num_rating_df=num_rating_df.rename(columns={"Book-Rating":"num-ratings"})

In [74]:
num_rating_df[num_rating_df['Book-Title'] == 'The Alchemist']

           Book-Title  num-ratings
175094  The Alchemist           13

In [26]:
num_rating_df[num_rating_df["num-ratings"]>250]

                                               Book-Title  num-ratings
764                                                  1984          284
818                                   1st to Die: A Novel          509
1048                                           2nd Chance          356
1760                                   A Bend in the Road          346
2281    A Child Called \It\": One Child's Courage to S...          265
...                                                   ...          ...
233850                           White Oleander : A Novel          387
233851       White Oleander : A Novel (Oprah's Book Club)          356
234740  Wicked: The Life and Times of the Wicked Witch...          326
234951                                        Wild Animus         2502
240860                                \O\" Is for Outlaw"          269

[186 rows x 2 columns]

In [75]:
avg_rating_df=ratings_with_name.groupby("Book-Title").mean()["Book-Rating"].reset_index()
avg_rating_df.rename(columns={"Book-Rating":"avg-ratings"},inplace=True)
avg_rating_df

           Book-Title  avg-ratings
175094  The Alchemist     1.538462

In [28]:
popular_df=num_rating_df.merge(avg_rating_df, on="Book-Title")
popular_df

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [29]:
popular_df=popular_df[popular_df["num-ratings"]>=250].sort_values('avg-ratings', ascending=False).head(50)

In [30]:
popular_df

,Book-Title,num-ratings,avg-ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279
170101,Suzanne's Diary for Nicholas,457,3.820569
111073,Lord of the Flies,259,3.818533
5664,A Prayer for Owen Meany,413,3.796610
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472

In [31]:
popular_df=popular_df.merge(books, on="Book-Title").drop_duplicates("Book-Title")[["Book-Title","Book-Author","Image-URL-M","num-ratings","avg-ratings"]]

In [32]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num-ratings,avg-ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

In [72]:
ratings_with_name[ratings_with_name['Book-Title'] == 'The Alchemist']

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
595433,22900,0553255983,0,The Alchemist,Ken Goddard,1986,Bantam Books,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...
595434,100822,0553255983,0,The Alchemist,Ken Goddard,1986,Bantam Books,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...
595435,263877,0553255983,0,The Alchemist,Ken Goddard,1986,Bantam Books,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...
649958,30511,0747504687,6,The Alchemist,Mark Illis,1990,Bloomsbury Publishing Plc,http://images.amazon.com/images/P/0747504687.0...,http://images.amazon.com/images/P/0747504687.0...,http://images.amazon.com/images/P/0747504687.0...
815699,76499,0393900568,5,The Alchemist,Ben Jonson,1991,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393900568.0...,http://images.amazon.com/images/P/0393900568.0...,http://images.amazon.com/images/P/0393900568.0...
859108,98391,0345441141,9,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
859109,111847,0345441141,0,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
859110,121986,0345441141,0,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
859111,138441,0345441141,0,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
859112,178199,0345441141,0,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
934858,153662,0380000784,0,The Alchemist,Leslie H. Whitten,1976,Avon Books,http://images.amazon.com/images/P/0380000784.0...,http://images.amazon.com/images/P/0380000784.0...,http://images.amazon.com/images/P/0380000784.0...
969662,188796,8485982665,0,The Alchemist,Jorge A. Livraga Rizzi,2001,New Acropolis Cultural Assn,http://images.amazon.com/images/P/8485982665.0...,http://images.amazon.com/images/P/8485982665.0...,http://images.amazon.com/images/P/8485982665.0...
984598,204864,034546236X,0,The Alchemist,Donna Boyd,2003,Ballantine Books,http://images.amazon.com/images/P/034546236X.0...,http://images.amazon.com/images/P/034546236X.0...,http://images.amazon.com/images/P/034546236X.0...

## Collaborative Filtering for recommendation system

In [33]:
x=ratings_with_name.groupby("User-ID").count()["Book-Rating"] > 200
intellect_users=x[x].index

In [34]:
x[x]

User-ID
254       True
2276      True
2766      True
2977      True
3363      True
          ...
274308    True
275970    True
277427    True
277639    True
278418    True
Name: Book-Rating, Length: 811, dtype: bool

In [35]:
filtered_rating=ratings_with_name[ratings_with_name["User-ID"].isin(intellect_users)]

In [36]:
y=filtered_rating.groupby('Book-Title').count()["Book-Rating"]>=50
famous_books=y[y].index

In [37]:
famous_books

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Day Late and a Dollar Short', 'A Fine Balance',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='Book-Title', length=706)

In [38]:
final_ratings=filtered_rating[filtered_rating["Book-Title"].isin(famous_books)]

In [39]:
pt=final_ratings.pivot_table(index="Book-Title", columns="User-ID", values="Book-Rating")

In [40]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [41]:
pt.fillna(0,inplace=True)

In [42]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity_scores=cosine_similarity(pt)

In [45]:
similarity_scores[704]

array([0.07347567, 0.16773875, 0.04938579, 0.        , 0.11284126,
       0.11224972, 0.1536172 , 0.07070243, 0.13194105, 0.0879174 ,
       0.09394598, 0.        , 0.0722577 , 0.08751563, 0.19013896,
       0.08838835, 0.13847624, 0.0493197 , 0.10184887, 0.06381997,
       0.12381007, 0.        , 0.12535646, 0.08885599, 0.13360872,
       0.        , 0.05969674, 0.06236096, 0.16039401, 0.06786258,
       0.03106883, 0.05959444, 0.        , 0.30199543, 0.        ,
       0.14389473, 0.04492721, 0.22358045, 0.10559799, 0.19520018,
       0.        , 0.0803096 , 0.03598302, 0.04895763, 0.05785163,
       0.17427718, 0.        , 0.07634573, 0.09451121, 0.11624778,
       0.09408918, 0.10399847, 0.        , 0.10328147, 0.0777027 ,
       0.        , 0.1270828 , 0.02257064, 0.13786105, 0.05758289,
       0.07193131, 0.        , 0.05018676, 0.32252503, 0.        ,
       0.0840875 , 0.07884165, 0.        , 0.10081854, 0.02776016,
       0.        , 0.        , 0.13552619, 0.02218391, 0.08678529,
       0.17466292, 0.10571172, 0.14191418, 0.0538667 , 0.13986684,
       0.04838983, 0.0551543 , 0.03744988, 0.        , 0.02880927,
       0.11734116, 0.08345508, 0.23464769, 0.20649776, 0.03442023,
       0.15294651, 0.        , 0.09915372, 0.0473939 , 0.04323954,
       0.09456641, 0.17245759, 0.13815491, 0.08801585, 0.        ,
       0.14706332, 0.05122408, 0.05673486, 0.18196004, 0.05004036,
       0.        , 0.12199809, 0.14982415, 0.11366992, 0.14217433,
       0.08560993, 0.08486251, 0.        , 0.070903  , 0.15106991,
       0.        , 0.07850611, 0.06702671, 0.1224465 , 0.        ,
       0.10475219, 0.12512225, 0.0571929 , 0.15542707, 0.        ,
       0.27040431, 0.11954997, 0.04847862, 0.08207251, 0.30166404,
       0.16039074, 0.        , 0.        , 0.        , 0.        ,
       0.03508472, 0.        , 0.08494859, 0.21780586, 0.06836967,
       0.09752369, 0.1137035 , 0.193524  , 0.12279207, 0.07333412,
       0.        , 0.        , 0.03464498, 0.21721954, 0.08837739,
       0.        , 0.0887082 , 0.1293153 , 0.11729877, 0.11002114,
       0.        , 0.13048581, 0.        , 0.05235998, 0.03568828,
       0.06524148, 0.07845789, 0.0518354 , 0.10561435, 0.12105521,
       0.13372326, 0.18678098, 0.10790449, 0.05796191, 0.0648697 ,
       0.13310348, 0.25329442, 0.11091377, 0.        , 0.07832725,
       0.43416882, 0.        , 0.29381356, 0.11444015, 0.        ,
       0.07940367, 0.05365305, 0.06131864, 0.12725235, 0.08859036,
       0.08145166, 0.19690497, 0.0664619 , 0.04496769, 0.14764384,
       0.        , 0.        , 0.20695287, 0.08438265, 0.6188332 ,
       0.035375  , 0.43104197, 0.03914724, 0.02674797, 0.04641669,
       0.09951809, 0.        , 0.12043261, 0.0611761 , 0.        ,
       0.15202367, 0.09924804, 0.17091713, 0.09916705, 0.05956045,
       0.        , 0.12742802, 0.35566827, 0.        , 0.04602418,
       0.06051198, 0.14154454, 0.0672296 , 0.15180418, 0.        ,
       0.09844763, 0.01103777, 0.        , 0.        , 0.08082664,
       0.05397005, 0.09245365, 0.10862738, 0.09289965, 0.04481239,
       0.07026865, 0.04915486, 0.09132241, 0.14569681, 0.1419632 ,
       0.39451749, 0.07977448, 0.        , 0.13547929, 0.08637948,
       0.0769947 , 0.08471556, 0.20299042, 0.20000416, 0.07483689,
       0.16149813, 0.10095218, 0.18869453, 0.        , 0.07309709,
       0.12774976, 0.09484491, 0.04993873, 0.14661391, 0.04692084,
       0.        , 0.08547043, 0.06559938, 0.10651048, 0.1667388 ,
       0.18120789, 0.04522711, 0.13527281, 0.        , 0.        ,
       0.1720842 , 0.10589446, 0.1209255 , 0.08514223, 0.03201859,
       0.06168761, 0.094246  , 0.12085593, 0.        , 0.        ,
       0.10308516, 0.09569209, 0.19499714, 0.14663662, 0.15955275,
       0.18405254, 0.        , 0.03584022, 0.11652692, 0.17528437,
       0.09765554, 0.07126158, 0.10684515, 0.45369362, 0.13570593,
       0.18836364, 0.14174749, 0.0476451 , 0.04933844, 0.17153098,
       0.05100258, 0.09606436, 0.03449202, 0.11905304, 0.09071295,
       0.10029718, 0.21238663, 0.08025827, 0.27441815, 0.07517598,
       0.09782186, 0.06948083, 0.04041317, 0.        , 0.05244398,
       0.08131636, 0.11213484, 0.06491708, 0.1289093 , 0.10439996,
       0.1328955 , 0.        , 0.        , 0.05503231, 0.09172492,
       0.06999563, 0.409452  , 0.01970595, 0.03457129, 0.08914395,
       0.1848403 , 0.07839861, 0.        , 0.07557747, 0.10790449,
       0.32290542, 0.23075163, 0.07410676, 0.18874936, 0.        ,
       0.09709679, 0.        , 0.0430104 , 0.08709629, 0.11918887,
       0.        , 0.20745228, 0.04833279, 0.03857785, 0.05112241,
       0.14146627, 0.10739426, 0.05374494, 0.        , 0.12702112,
       0.17026118, 0.        , 0.08114461, 0.29414076, 0.03308611,
       0.13556374, 0.3292129 , 0.        , 0.15775724, 0.11891768,
       0.        , 0.17336571, 0.06871731, 0.11708568, 0.15409613,
       0.1748791 , 0.        , 0.08708766, 0.08558961, 0.11565224,
       0.0726981 , 0.        , 0.08765349, 0.09394879, 0.12902957,
       0.12272839, 0.06907046, 0.        , 0.        , 0.21538176,
       0.24146414, 0.05495311, 0.07108537, 0.09996827, 0.07287714,
       0.24218083, 0.032706  , 0.        , 0.104108  , 0.03352546,
       0.        , 0.        , 0.04815841, 0.09166765, 0.11229507,
       0.09293722, 0.22681618, 0.02518859, 0.        , 0.        ,
       0.18483956, 0.0625363 , 0.        , 0.10307948, 0.06781112,
       0.        , 0.        , 0.        , 0.        , 0.07965733,
       0.06874888, 0.09421363, 0.08038864, 0.04472647, 0.10307253,
       0.03624657, 0.19256999, 0.16180574, 0.13003495, 0.18477356,
       0.13265963, 0.07560154, 0.12031476, 0.06948083, 0.54239174,
       0.06263998, 0.06799643, 0.10918719, 0.        , 0.09084208,
       0.1510813 , 0.06674749, 0.05940606, 0.        , 0.05657501,
       0.07115182, 0.08204127, 0.        , 0.06324154, 0.05367039,
       0.17475563, 0.08563412, 0.        , 0.11209161, 0.11901971,
       0.0930678 , 0.09323748, 0.05451832, 0.14559399, 0.        ,
       0.06562965, 0.        , 0.0981606 , 0.        , 0.05327856,
       0.12825257, 0.        , 0.13022071, 0.05245543, 0.03593799,
       0.0695288 , 0.10845384, 0.22532595, 0.01451553, 0.        ,
       0.11426939, 0.0591088 , 0.05238983, 0.07754035, 0.        ,
       0.06934987, 0.        , 0.25375761, 0.        , 0.1304647 ,
       0.        , 0.12293206, 0.087792  , 0.07118965, 0.        ,
       0.18974383, 0.09899425, 0.11207252, 0.02353663, 0.        ,
       0.        , 0.11338233, 0.0431401 , 0.05803588, 0.08664381,
       0.05949196, 0.12331942, 0.        , 0.        , 0.10163195,
       0.02669567, 0.17033054, 0.07383572, 0.        , 0.04834802,
       0.07262973, 0.14585118, 0.13366626, 0.05074248, 0.04328581,
       0.12146294, 0.18916751, 0.11307427, 0.06579743, 0.09837104,
       0.278262  , 0.        , 0.16867401, 0.        , 0.12086589,
       0.07454033, 0.06800834, 0.04951388, 0.17404158, 0.        ,
       0.        , 0.09248115, 0.        , 0.        , 0.13900961,
       0.        , 0.13756674, 0.06305962, 0.11241719, 0.14155624,
       0.15805052, 0.08765667, 0.08819171, 0.09374765, 0.10084135,
       0.08390463, 0.10064935, 0.16424181, 0.06526237, 0.09619007,
       0.01736219, 0.13550662, 0.08754297, 0.07037093, 0.        ,
       0.04876987, 0.02435847, 0.        , 0.07115359, 0.05511745,
       0.07575199, 0.03901917, 0.14989711, 0.09681488, 0.13030289,
       0.06098727, 0.05014347, 0.11664514, 0.02096652, 0.1       ,
       0.14714655, 0.09881842, 0.06716183, 0.04381547, 0.15301786,
       0.        , 0.31419543, 0.0777531 , 0.1393814 , 0.09264111,
       0.05657187, 0.07086834, 0.        , 0.07599499, 0.        ,
       0.        , 0.08234066, 0.06157774, 0.        , 0.10247707,
       0.        , 0.17042346, 0.17502926, 0.05967966, 0.0926971 ,
       0.18692242, 0.0631604 , 0.0920714 , 0.0932528 , 0.02759343,
       0.09246278, 0.        , 0.27120739, 0.08582347, 0.        ,
       0.19556947, 0.13159034, 0.09432714, 0.08167814, 0.10089227,
       0.06897138, 0.13132033, 0.12060192, 0.        , 0.06910252,
       0.03714347, 0.12628312, 0.27103884, 0.        , 0.08457533,
       0.1053769 , 0.06791855, 0.11726626, 0.10539067, 0.00702684,
       0.0668815 , 0.07982062, 0.        , 0.06530033, 0.0843274 ,
       0.14930053, 0.07713069, 0.07557932, 0.13280717, 0.04923233,
       0.06761462, 0.06019877, 0.10014609, 0.11908571, 0.04239855,
       0.17786945, 0.03081292, 0.19183052, 0.        , 0.04892937,
       0.04343072, 0.07407407, 0.14983884, 0.08243693, 0.        ,
       0.16383308, 0.18049542, 0.11397379, 0.1048831 , 0.06961936,
       0.        , 0.20199529, 0.09227488, 0.06401844, 0.15243294,
       0.02472773, 0.05713619, 0.15518559, 0.09965261, 0.1619187 ,
       0.0857565 , 0.12166607, 0.11152768, 0.0610197 , 0.24887298,
       0.0860663 , 0.06109032, 0.23011971, 0.28716367, 0.14523373,
       0.06639519, 0.09096289, 0.11710074, 0.12137604, 0.        ,
       0.07060988, 0.32339517, 0.20655767, 0.03838645, 0.13016854,
       0.08026721, 0.10871644, 0.18673624, 0.08361376, 0.        ,
       0.07440815, 0.        , 0.13914717, 0.14773421, 0.        ,
       0.02955363, 0.14118624, 0.        , 0.09405111, 0.13173062,
       0.07271563, 0.        , 0.0582489 , 0.19756552, 0.06614378,
       0.15106991, 0.11076376, 0.04612189, 0.03918664, 0.08309625,
       0.0368073 , 0.08133024, 0.19430288, 0.07085128, 1.        ,
       0.10602962])

In [65]:
def recommend(book_name):
    index=np.where(pt.index==book_name)[0][0]
    similar_items=sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[1:6]
    data=[]
    for i in similar_items:
        item=[]
        temp_df=books[books['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [70]:
recommend('The Alchemist')

IndexError: index 0 is out of bounds for axis 0 with size 0

In [48]:
import pickle 
pickle.dump(popular_df,open('popular.pkl','wb'))

In [67]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))

In [69]:
books[books['Book-Title'] == 'The Alchemist']

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
40015,0553255983,The Alchemist,Ken Goddard,1986,Bantam Books,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...,http://images.amazon.com/images/P/0553255983.0...
57670,0747504687,The Alchemist,Mark Illis,1990,Bloomsbury Publishing Plc,http://images.amazon.com/images/P/0747504687.0...,http://images.amazon.com/images/P/0747504687.0...,http://images.amazon.com/images/P/0747504687.0...
129271,0345441141,The Alchemist,DONNA BOYD,2002,Ballantine Books,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...,http://images.amazon.com/images/P/0345441141.0...
197978,0393900568,The Alchemist,Ben Jonson,1991,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393900568.0...,http://images.amazon.com/images/P/0393900568.0...,http://images.amazon.com/images/P/0393900568.0...
201515,8485982665,The Alchemist,Jorge A. Livraga Rizzi,2001,New Acropolis Cultural Assn,http://images.amazon.com/images/P/8485982665.0...,http://images.amazon.com/images/P/8485982665.0...,http://images.amazon.com/images/P/8485982665.0...
217188,0380000784,The Alchemist,Leslie H. Whitten,1976,Avon Books,http://images.amazon.com/images/P/0380000784.0...,http://images.amazon.com/images/P/0380000784.0...,http://images.amazon.com/images/P/0380000784.0...
258305,034546236X,The Alchemist,Donna Boyd,2003,Ballantine Books,http://images.amazon.com/images/P/034546236X.0...,http://images.amazon.com/images/P/034546236X.0...,http://images.amazon.com/images/P/034546236X.0...